### ISSUE TITLE
error while installing in docker

### ISSUE THREAD

**Issue by god-of-javascript** [gjtorikian/commonmarker#280] opened 2024-03-19 00:11 UTC
Hi,

I have installed this gem and it works perfect in my local, but in github CD when we are building image I don't understand why It is not working fine.
it gives this error:
```bash
#13 1223.0 error: cannot produce cdylib for `commonmarker v1.0.0
#13 1223.0 (/gems/ruby/3.2.0/gems/commonmarker-1.0.4/ext/commonmarker)` as the target
#13 1223.0 `x86_64-unknown-linux-musl` does not support these crate types
#13 1223.0 make: *** [Makefile:565: target/release/libcommonmarker.so] Error 101
#13 1223.0 
#13 1223.0 make failed, exit code 2
```

any idea how to fix it?

**Comment by gjtorikian** [comment] 2024-03-19 13:13
Duplicate of https://github.com/gjtorikian/commonmarker/issues/272

**Closed by gjtorikian** 2024-03-19 13:13 UTC
